- name: Create the PKI
  hosts: localhost
  connection: local
  roles:
    - pki

- name: Generate the Kubeconfig files
  hosts: localhost
  connection: local
  roles:
    - kubeconfig

- name: Download the k8s components
  hosts: localhost
  connection: local
  roles:
    - k8s-download

- name: Deploy loadbalancer
  hosts: loadbalancer
  remote_user: vagrant
  become: yes
  roles:
    - loadbalancer

- name: Deploy Etcd cluster
  hosts: k8s-masters
  remote_user: vagrant
  become: yes
  roles:
    - etcd

- name: Deploy k8s master components
  hosts: k8s-masters
  remote_user: vagrant
  become: yes
  roles:
    - k8s-master

- name: Deploy k8s worker components
  hosts: k8s-workers
  remote_user: vagrant
  become: yes
  roles:
    - k8s-worker

- name: Install add-ons
  hosts: localhost
  roles:
    - addons

- name: Setup the monitoring stack
  hosts: localhost
  roles:
    - k8s-monitoring
