---

- name: Generate pki certificates
  shell: "./cfssl.sh"
  args:
    chdir: scripts

- name: Generate kubeconfig files
  shell: "./kubectl_conf.sh"
  args:
    chdir: scripts

- name: Create bin directory
  file:
    path: bin
    state: directory

- name: Download k8s binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: 0664
  with_items:
    - { url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/kube-apiserver", dest: "bin/kube-apiserver" }
    - { url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/kube-controller-manager", dest: "bin/kube-controller-manager" }
    - { url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/kube-scheduler", dest: "bin/kube-scheduler" }
    - { url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/kubelet", dest: "bin/kubelet" }
    - { url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s_version }}/bin/linux/amd64/kube-proxy", dest: "bin/kube-proxy" }

- name: Download Flannel
  get_url:
    url: https://github.com/coreos/flannel/releases/download/{{ flannel_version }}/flannel-{{ flannel_version }}-linux-amd64.tar.gz
    dest: bin/flannel-{{ flannel_version }}-linux-amd64.tar.gz
    mode: 0644

- name: Download Etcd
  get_url:
    url: https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: bin/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    mode: 0644

- name: Extract Flannel archive
  unarchive:
    src: ../../bin/flannel-{{ flannel_version }}-linux-amd64.tar.gz
    dest: "{{ playbook_dir }}/bin/"
    exclude: 
      - mk-docker-opts.sh
      - README.md
    mode: 0554

- name: Extract Etcd archive
  unarchive:
    src: ../../bin/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: "{{ playbook_dir }}/bin/"
    exclude: 
      - Documentation
      - README-etcdctl.md  
      - README.md  
      - READMEv2-etcdctl.md
    extra_opts: "--strip-components=1"
