---

- name: Add Docker key
  apt_key:
    url: "{{ docker_key }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: copy systemd unit file
  template:
    src: "lib/systemd/system/docker.service.j2"
    dest: "/lib/systemd/system/docker.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart docker
  tags: 
    - config

- meta: flush_handlers
